export type SpeciesCategoryId =
  | "all"
  | "companion"
  | "livestock"
  | "birds"
  | "aquatic"
  | "exotic";

export type SpeciesCategory = {
  id: SpeciesCategoryId;
  label: string;
};

export type Species = {
  latin: string;
  common: string;
  col: number;
  img: string;
  category: Exclude<SpeciesCategoryId, "all">;
  entrusted: string;
};

export const CATEGORIES: SpeciesCategory[] = [
  { id: "all", label: "ALL" },
  { id: "companion", label: "COMPANION" },
  { id: "livestock", label: "LIVESTOCK" },
  { id: "birds", label: "BIRDS" },
  { id: "aquatic", label: "AQUATIC" },
  { id: "exotic", label: "EXOTIC" },
];

export const SPECIES: Species[] = [
  {
    latin: "Equine",
    common: "Horse",
    col: 0,
    img: "/images/animals/horse.png",
    category: "livestock",
    entrusted: "A rider, a rancher, a kid at a lesson barn.",
  },
  {
    latin: "Bovine",
    common: "Cattle",
    col: 1,
    img: "/images/animals/cattle.png",
    category: "livestock",
    entrusted: "A farmer up before dawn with a whole herd to protect.",
  },
  {
    latin: "Porcine",
    common: "Pig",
    col: 2,
    img: "/images/animals/pig.png",
    category: "livestock",
    entrusted: "A smallholder who knows every animal by temperament.",
  },
  {
    latin: "Ovine",
    common: "Sheep",
    col: 3,
    img: "/images/animals/sheep.png",
    category: "livestock",
    entrusted: "A shepherd watching weather and pasture like vital signs.",
  },
  {
    latin: "Caprine",
    common: "Goat",
    col: 4,
    img: "/images/animals/goat.png",
    category: "livestock",
    entrusted: "A homestead family counting on milk, land, and luck.",
  },
  {
    latin: "Asinine",
    common: "Donkey",
    col: 0,
    img: "/images/animals/donkey.png",
    category: "livestock",
    entrusted: "A working partner on rough ground where trucks can't go.",
  },
  {
    latin: "Camelid",
    common: "Camel",
    col: 1,
    img: "/images/animals/camel.png",
    category: "livestock",
    entrusted: "A herder crossing distances where clinics are rare.",
  },
  {
    latin: "Alpaca",
    common: "Alpaca",
    col: 2,
    img: "/images/animals/alpaca.png",
    category: "livestock",
    entrusted: "A fiber farmer reading body language like a chart.",
  },
  {
    latin: "Bubaline",
    common: "Buffalo",
    col: 3,
    img: "/images/animals/buffalo.png",
    category: "livestock",
    entrusted: "A dairy family whose livelihood walks on four legs.",
  },
  {
    latin: "Canine",
    common: "Dog",
    col: 4,
    img: "/images/animals/dog.png",
    category: "companion",
    entrusted: "A person who would drive all night for an ER visit.",
  },
  {
    latin: "Feline",
    common: "Cat",
    col: 0,
    img: "/images/animals/cat.png",
    category: "companion",
    entrusted: "Someone who notices the quiet changes first.",
  },
  {
    latin: "Cunicular",
    common: "Rabbit",
    col: 1,
    img: "/images/animals/rabbit.png",
    category: "companion",
    entrusted: "A child learning what it means to keep another life safe.",
  },
  {
    latin: "Musteline",
    common: "Ferret",
    col: 2,
    img: "/images/animals/ferret.png",
    category: "companion",
    entrusted: "An owner fluent in a species most clinics rarely see.",
  },
  {
    latin: "Cavy",
    common: "Guinea Pig",
    col: 3,
    img: "/images/animals/guinea_pig.png",
    category: "companion",
    entrusted: "A family that treats a small life as fully sacred.",
  },
  {
    latin: "Rattus",
    common: "Rat",
    col: 4,
    img: "/images/animals/rat.png",
    category: "companion",
    entrusted: "A caretaker who knows smart animals still need medicine.",
  },
  {
    latin: "Gallus",
    common: "Chicken",
    col: 0,
    img: "/images/animals/chicken.png",
    category: "birds",
    entrusted: "A backyard flock keeper watching for the first limp.",
  },
  {
    latin: "Anatine",
    common: "Duck",
    col: 1,
    img: "/images/animals/duck.png",
    category: "birds",
    entrusted: "Someone balancing pond, feed, and fragile ducklings.",
  },
  {
    latin: "Meleagrine",
    common: "Turkey",
    col: 2,
    img: "/images/animals/turkey.png",
    category: "birds",
    entrusted: "A farm hand responsible when the flock thins.",
  },
  {
    latin: "Anserine",
    common: "Goose",
    col: 3,
    img: "/images/animals/goose.png",
    category: "birds",
    entrusted: "A guardian of birds that guard the yard in return.",
  },
  {
    latin: "Psittacine",
    common: "Parrot",
    col: 4,
    img: "/images/animals/parrot.png",
    category: "birds",
    entrusted: "A lifelong companion to a bird that may outlive them.",
  },
  {
    latin: "Cockatiel",
    common: "Cockatiel",
    col: 0,
    img: "/images/animals/cockatiel.png",
    category: "birds",
    entrusted: "An apartment caretaker learning avian subtlety.",
  },
  {
    latin: "Serinus",
    common: "Canary",
    col: 1,
    img: "/images/animals/canary.png",
    category: "birds",
    entrusted: "Someone who hears illness before they see it.",
  },
  {
    latin: "Columbine",
    common: "Dove",
    col: 2,
    img: "/images/animals/dove.png",
    category: "birds",
    entrusted: "A quiet steward of a gentle, easily stressed life.",
  },
  {
    latin: "Passerine",
    common: "Finch",
    col: 3,
    img: "/images/animals/finch.png",
    category: "birds",
    entrusted: "A keeper of tiny birds with outsized needs.",
  },
  {
    latin: "Strigine",
    common: "Owl",
    col: 4,
    img: "/images/animals/owl.png",
    category: "birds",
    entrusted: "A rehabber standing between injury and release.",
  },
  {
    latin: "Cyprinine",
    common: "Koi",
    col: 0,
    img: "/images/animals/koi.png",
    category: "aquatic",
    entrusted: "A pond keeper treating water quality as medicine.",
  },
  {
    latin: "Auratus",
    common: "Goldfish",
    col: 1,
    img: "/images/animals/goldfish.png",
    category: "aquatic",
    entrusted: "A first pet that still deserves a real standard of care.",
  },
  {
    latin: "Betta",
    common: "Betta Fish",
    col: 2,
    img: "/images/animals/betta_fish.png",
    category: "aquatic",
    entrusted: "Someone who refused to leave a fish in a cup.",
  },
  {
    latin: "Testudinid",
    common: "Tortoise",
    col: 3,
    img: "/images/animals/tortoise.png",
    category: "exotic",
    entrusted: "A multi-decade promise to a life that moves slowly.",
  },
  {
    latin: "Iguanid",
    common: "Iguana",
    col: 4,
    img: "/images/animals/iguana.png",
    category: "exotic",
    entrusted: "An exotic-pet owner hunting scarce reptile expertise.",
  },
  {
    latin: "Uroplatus",
    common: "Gecko",
    col: 0,
    img: "/images/animals/gecko.png",
    category: "exotic",
    entrusted: "A night-shift caretaker watching temperature like a vital.",
  },
  {
    latin: "Colubrid",
    common: "Corn Snake",
    col: 1,
    img: "/images/animals/corn_snake.png",
    category: "exotic",
    entrusted: "Someone translating shed, appetite, and stillness into care.",
  },
  {
    latin: "Hamster",
    common: "Hamster",
    col: 2,
    img: "/images/animals/hamster.png",
    category: "companion",
    entrusted:
      "A child learning responsibility one small heartbeat at a time.",
  },
  {
    latin: "Chinchilla",
    common: "Chinchilla",
    col: 3,
    img: "/images/animals/chinchilla.png",
    category: "companion",
    entrusted: "A careful owner protecting a delicate physiology.",
  },
  {
    latin: "Degu",
    common: "Degu",
    col: 4,
    img: "/images/animals/degu.png",
    category: "companion",
    entrusted: "A niche-species caretaker with few textbooks to lean on.",
  },
  {
    latin: "Axolotl",
    common: "Axolotl",
    col: 0,
    img: "/images/animals/axolotl.png",
    category: "aquatic",
    entrusted:
      "A keeper balancing regeneration myth with real water chemistry.",
  },
  {
    latin: "Pacos",
    common: "Llama",
    col: 1,
    img: "/images/animals/llama.png",
    category: "livestock",
    entrusted: "A ranch hand reading herd dynamics for early distress.",
  },
  {
    latin: "Yak",
    common: "Yak",
    col: 2,
    img: "/images/animals/yak.png",
    category: "livestock",
    entrusted: "A high-country herder far from specialty medicine.",
  },
  {
    latin: "Tarantula",
    common: "Tarantula",
    col: 3,
    img: "/images/animals/tarantula.png",
    category: "exotic",
    entrusted: "An invertebrate keeper who still needs clinical answers.",
  },
  {
    latin: "Meriones",
    common: "Gerbil",
    col: 4,
    img: "/images/animals/gerbil.png",
    category: "companion",
    entrusted: "A family treating a pocket pet as a full patient.",
  },
  {
    latin: "Pavo",
    common: "Peacock",
    col: 0,
    img: "/images/animals/peacock.png",
    category: "birds",
    entrusted: "A groundskeeper responsible for birds that draw a crowd.",
  },
  {
    latin: "Erinaceus",
    common: "Hedgehog",
    col: 1,
    img: "/images/animals/hedgehog.png",
    category: "companion",
    entrusted: "An exotic-mammal owner navigating sparse protocols.",
  },
  {
    latin: "Columba",
    common: "Pigeon",
    col: 2,
    img: "/images/animals/pigeon.png",
    category: "birds",
    entrusted: "A loft keeper for birds that fly home and get hurt.",
  },
  {
    latin: "Coturnix",
    common: "Quail",
    col: 3,
    img: "/images/animals/quail.png",
    category: "birds",
    entrusted: "A small-flock farmer watching for silent disease.",
  },
  {
    latin: "Vulpes",
    common: "Fox",
    col: 4,
    img: "/images/animals/fox.png",
    category: "exotic",
    entrusted: "A wildlife rehabber racing the clock of trauma.",
  },
  {
    latin: "Lutra",
    common: "Otter",
    col: 0,
    img: "/images/animals/otter.png",
    category: "aquatic",
    entrusted: "A rehab team managing aquatic mammals with few precedents.",
  },
  {
    latin: "Petaurus",
    common: "Sugar Glider",
    col: 1,
    img: "/images/animals/sugar_glider.png",
    category: "exotic",
    entrusted: "A nocturnal-pet caretaker learning a rare species by heart.",
  },
  {
    latin: "Apis",
    common: "Bee",
    col: 2,
    img: "/images/animals/bee.png",
    category: "exotic",
    entrusted: "A beekeeper treating the colony as one living patient.",
  },
  {
    latin: "Cervid",
    common: "Deer",
    col: 3,
    img: "/images/animals/deer.png",
    category: "exotic",
    entrusted: "A wildlife responder when the wild meets the road.",
  },
  {
    latin: "Aquila",
    common: "Eagle",
    col: 4,
    img: "/images/animals/eagle.png",
    category: "birds",
    entrusted: "A raptor rehabber restoring flight and dignity.",
  },
];

/** Card background palette indexed by species.col */
export const SPECIES_CARD_COLORS = [
  "#0057ff",
  "#0b1f3a",
  "#e8f2ff",
  "#ddeeff",
  "#f7f3ec",
] as const;
